adds library page
neuland-ingolstadt/neuland.app-native pull request #60
Opened 2023-11-16 13:35 UTC by Robert27

2023-11-17 23:47 UTC, BuildmodeOne requested changes
Only a partial review on the train (and smartphone lol)🚂
Will review the rest later :)

2023-11-17 23:47 UTC, BuildmodeOne commented on package.json
> -  "packageManager": "yarn@4.0.1",
Windows will probably always add this back.

2023-11-17 23:47 UTC, BuildmodeOne commented on src/app/(tabs)/timetable.tsx
> +            setLoadingState(LoadingState.ERROR)
Is this correct?

2023-11-17 23:47 UTC, BuildmodeOne commented on src/localization/de/navigation.ts
> +        libraryCode: 'Bibliotheks Code',
On the student ID it's called "Bibliotheksnummer"

2023-11-17 23:47 UTC, BuildmodeOne commented on src/localization/en/navigation.ts
> +        libraryCode: 'Library Code',
Would prefer number here as well.

2023-11-21 12:57 UTC, BuildmodeOne submitted a review, later dismissed
lgtm

2023-11-21 12:57 UTC, BuildmodeOne commented on src/localization/en/common.ts
> +                    confirm: 'Delete',
This key can be removed

2023-11-21 12:59 UTC, BuildmodeOne approved these changes
lgtm

2023-11-21 12:59 UTC, Robert27 reviewed
thanks for the review

2023-11-21 13:00 UTC, merged